// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knazdiiqpmhsysayfhat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYXpkaWlxcG1oc3lzYXlmaGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzIzMzAsImV4cCI6MjA2NTA0ODMzMH0.T9MRXnMckMW5MhOvAZg2IndJDG_pR4r1eT_37BJfEYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);